name: Github Action demo - parthshiras

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      -main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # this step checks out the repository that you are working from
      - name: Output the name of the event that triggered my workflow
        run: echo "Event name: ${{ github.event_name }}"
      - name: Output the name of the branch
        uses: echo "Branch name: $(echo ${{ github.ref }})"
      - name: List all the files in the repository
        run: |
          echo "List of files:" 
          ls -R
