name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # This step checks out the repository
      - name: Output the name of the event that triggered the workflow
        run: echo "Event name:${{ github.event_name }}"
      - name: Output the name of the branch
        run: echo "Branch name:$(echo ${{ github.ref }} | sed 's/refs\/heads\///')"
      - name: List all files in the repository
        run: |
          echo "List of files in the repository:"
          ls -R
